name: Create source release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get version tag
        id: get_tag
        run: |
          [[ ! "$GITHUB_REF" =~ refs/tags ]] && exit
          echo "::set-output name=value::${GITHUB_REF#refs/tags/v}"

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Build source archive and wheel
        shell: bash
        run: |
          pip install wheel
          python setup.py sdist
          python setup.py bdist_wheel

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: "heisenbridge-${{ steps.get_tag.outputs.value }}.tar.gz"
          path: "dist/heisenbridge-${{ steps.get_tag.outputs.value }}.tar.gz"

      - name: Upload tagged release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.get_tag.outputs.value }}"
          files: |
            dist/heisenbridge-${{ steps.get_tag.outputs.value }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
